# Generated by Django 5.2.1 on 2025-05-13 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omega_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglist",
            name="invitation_token",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Token for invitation validation",
                null=True,
            ),
        ),
    ]
