# Generated by Django 5.2.1 on 2025-05-13 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManimScript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The user prompt used to generate the script"
                    ),
                ),
                ("script", models.TextField(help_text="The generated Manim script")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini"),
                            ("azure_openai", "Azure OpenAI"),
                        ],
                        help_text="AI provider used for generation",
                        max_length=20,
                    ),
                ),
                (
                    "script_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the saved script file",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "output_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the output video",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "output_url",
                    models.URLField(
                        blank=True,
                        help_text="Full URL to access the output video",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Status of the script execution",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if execution failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Manim Script",
                "verbose_name_plural": "Manim Scripts",
                "ordering": ["-created_at"],
            },
        ),
    ]
