# Generated by Django 5.2.1 on 2025-05-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omega", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manimscript",
            name="script_path",
        ),
    ]
